apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: alliance-auth-k8s
  name: auth-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
